name: bbb_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
    sdk: ">=2.3.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    cybex_flutter_plugin:
        git:
            url: git@github.com:CybexDex/cybex_flutter_plugin.git
            ref: develop
    dio: ^2.1.0
    charts_flutter: ^0.6.0
    qr_flutter: ^2.0.0
    jdenticon_dart: ^1.2.1+1
    flutter_svg:
        git:
            url: https://github.com/shefengl/flutter_svg

    flutter_page_indicator: ^0.0.3
    flutter_spinkit: ^3.1.0
    cached_network_image: ^0.7.0
    shared_preferences: ^0.5.2
    simple_animations: ^1.0.0
    magical_widget: ^1.0.1
    rosetta: ^0.1.2

    pointycastle: ^1.0.1
    vertical_tabs: ^0.1.4
    logger: ^0.6.0
    carousel_slider: ^1.3.0
    flutter_screenutil: ^0.5.2
    flutter_localizations:
        sdk: flutter # The following adds the Cupertino Icons font to your application.
    web_socket_channel: ^1.0.12
   
    cupertino_icons: ^0.1.2
    provider: ^3.0.0+1
    rxdart: ^0.22.0
    get_it: ^1.0.3+1
    quiver: '>=2.0.0 <3.0.0'
    oktoast: ^2.1.9
    rflutter_alert: ^1.0.3
    pull_to_refresh: ^1.4.7
    functional_widget_annotation: ^0.5.0
    json_annotation: ^2.4.0
    keyboard_avoider: ^0.1.2
    rx_command: ^4.3.1+1
    rx_widgets: ^2.2.0+1
#    flutter_flipperkit: ^0.0.18
dev_dependencies:
    flutter_test:
        sdk: flutter
    build_runner: any
    # functional_widget: any
    json_serializable: ^3.0.0
    rosetta_generator: any
flutter:
    uses-material-design: true

    assets:
    - i18n/
    # assets begin
    # res/assets/icons/*
    - res/assets/icons/icTop2.png
    - res/assets/icons/icTop3.png
    - res/assets/icons/icMaskClose.png
    - res/assets/icons/icTop1.png
    - res/assets/icons/icAdd.png
    - res/assets/icons/icReduce.png
    - res/assets/icons/icFail.png
    - res/assets/icons/icDownGreen14.png
    - res/assets/icons/icDropdown.png
    - res/assets/icons/icPerson.png
    - res/assets/icons/icWarn.png
    - res/assets/icons/icChange.png
    - res/assets/icons/icUpRed14.png
    - res/assets/icons/icSuccess.png
    - res/assets/icons/icPassword.png
    - res/assets/icons/icEmpty.png
    - res/assets/icons/icTabDeposit.png
    - res/assets/icons/icFallGreen.png
    - res/assets/icons/icTime.png
    - res/assets/icons/icNotifyBack.png
    - res/assets/icons/icSwitch.png
    - res/assets/icons/icAccount.png
    - res/assets/icons/icRiseRed18.png
    - res/assets/icons/icRevise.png
    - res/assets/icons/icCode.png
    - res/assets/icons/icUser.png
    - res/assets/icons/icHand.png
    - res/assets/icons/icUsdt.png
    - res/assets/icons/imgBanner.png
    - res/assets/icons/mask.png
    - res/assets/icons/icTabArrow.png
    - res/assets/icons/icTabWithdraw.png
    - res/assets/icons/ic_title_line.svg
    # assets end
